import React, {useEffect} from 'react';
import Head from 'next/head';

import LayoutMenu from './menu';

import styles from './index.module.css';

interface Props {
    children: React.ReactElement,
}
const Layout: React.FunctionComponent<Props> = ({
    children,
}) => {
    useEffect(() => {}, []);
    return (
        <div className='h-full w-full flex flex-col'>
            <Head>
                <title>QUOTE-ADMIN</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                <div className={styles.headerTitle}>QUOTE-ADMIN</div>
            </header>
            <main className='h-full flex-1 flex flex-row'>
                <LayoutMenu />
                <section className='flex-1 h-full '>
                    {children}
                </section>
            </main>
            {/* <footer className={styles.footer}>
                <a
                    href="https://github.com/orgs/ddupup/repositories"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    @ddupup github
                </a>
            </footer> */}
        </div>
    );
};
export default Layout;
