import type {NextPage} from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import LayoutComponent from '@components/layout';

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>QUOTE-ADMIN</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.main}>
                <header className={styles.header}>
                    <div className={styles.headerTitle}>QUOTE-ADMIN</div>
                </header>
            </div>
        </div>
    );
};

export default Home;
